service: layers-aws-issue

package:
  excludeDevDependencies: true
  include:
    - "!node_modules/**"
    - "!**/*.lock"

custom:
  region: ${opt:region, env:AWS_REGION, "us-east-1"}
  stage: ${opt:stage, env:STAGE, "sandbox"}

provider:
  name: aws
  runtime: nodejs8.10
  region: ${self:custom.region}
  stage: ${self:custom.stage}

# layers:
#   no-deps:
#     path: layers/no-deps
#   # serverless built-in _won't_ exclude devDeps nested in `nodejs`
#   with-deps:
#     path: layers/with-deps
#   # ... but Jetpack will with a `roots` configuration! (Special test excludes..)
#   with-deps-no-dev:
#     path: layers/with-deps
#     jetpack:
#       roots:
#         - layers/with-deps/nodejs
#   # serverless built-in _will_ exclude devDeps at root
#   with-deps-root:
#     path: layers/with-deps/nodejs

functions:
  base:
    handler: index.handler
    events: # Use a generic proxy to allow Express app to route.
      - http: ANY /base
      - http: 'ANY /base/{proxy+}'
